services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false  # Default visibility for services

    # Define your services here
    Skynettechnologies\ADABundle\Service\PageService:
        arguments:
            $logger: '@logger'

    # Controllers are imported separately to make sure they're public
    Skynettechnologies\ADABundle\Controller\:
        resource: '../src/Controller'
        public: true  # Ensure controllers are public

    # Register commands
    Skynettechnologies\ADABundle\Command\CreateDynamicPageCommand:
        arguments:
            $pageService: '@Skynettechnologies\ADABundle\Service\PageService'
        tags:
            - { name: 'console.command' }

    Skynettechnologies\ADABundle\Command\RemoveDynamicPageCommand:
        tags:
            - { name: 'console.command' }

    Skynettechnologies\ADABundle\ADAPimcoreBundle:
        public: true # Make sure the bundle is public
    Skynettechnologies\ADABundle\Twig\AppExtension:
        arguments:
            $adapimcoreBundle: '@Skynettechnologies\ADABundle\ADAPimcoreBundle'
        tags:
            - { name: twig.extension }
