ada_pimcore:
    resource: "@ADAPimcoreBundle/src/Controller/"
    type:     annotation
    prefix:   /

ada_setting:
    path: /ada-setting
    controller: Skynettechnologies\ADABundle\Controller\DefaultController::indexAction


